### ISSUE TITLE
utils: printBedModifications

### ISSUE THREAD

**Issue by lfpaulin** [DamarisLa/STRsimulator#13]
This function is very cryptic, need to be updated for readability

**Comment by DamarisLa** [comment]
@lfpaulin more readable now?

**Comment by lfpaulin** [comment]
Yes its better, there are just a couple of bugs to be fixed (assigning to myself)

**Comment by DamarisLa** [comment]
I think I ran the code now and get through to the end ;-)

**Comment by lfpaulin** [comment]
looks good to me
